### ISSUE TITLE
Can't hide transcript in paper edit view

### ISSUE THREAD

**Issue by bennuttall** [bbc/digital-paper-edit-firebase#103]
**Describe the bug**

The Paper Edit view shows a show/hide toggle for the two vertical panes: Transcripts and Program Script, and the Program Script 'hide' works but the Transcript one doesn't

![Screenshot 2020-05-07 at 18 02 25](https://user-images.githubusercontent.com/1609725/81323209-f183f680-908c-11ea-8baa-140fbaf26539.png)

**To Reproduce**

1. Go to a paper edit
1. Click "hide" on the Program Script, observe it working and click "show" to bring it back
1. Click "hide" on the Transcript", observe it not working

**Expected behavior**

Both the Program Script and the Transcript panes should be hideable - but only one at a time.

**Comment by aniablaziak** [comment]
Actually it looks like the 'hide' button for Programme script actually moves the element to the bottom of the page. Is the desired behaviour to hide it entirely instead? 

![1617979252802](https://user-images.githubusercontent.com/39386043/114197185-ff4f9500-9949-11eb-9be7-1c5638843f53.png)
