### ISSUE TITLE
Test large file uploads / investigate limits

### ISSUE THREAD

**Issue by bennuttall** [bbc/digital-paper-edit-firebase#107]
From the logs:

```
Error: 3 INVALID_ARGUMENT: The value of property "payload" is longer than 1048487 bytes.
```

Todo:

- Test large uploads, see how far they get
- Figure out a maximum file size
  - Is this acceptable as a limit?
  - Where is the limit?
  - If a limit must remain, ensure an error is shown when trying to upload a large enough file

**Comment by emettely** [comment]
Verified with 5h audio that it successfully uploaded. 🥳
