### ISSUE TITLE
Our version of user manual living in the web.

### ISSUE THREAD

**Issue by emettely** [bbc/digital-paper-edit-firebase#129]
@tamsingreen will break this down.

**Is your feature request related to a problem? Please describe.**
#127 

**Describe the solution you'd like**
We are currently linking to Pietro's version's (autoEdit3) user manual.
This might be a bit confusing because of the different names, UI, features, and will be more different over time, as autoEdit3 and DPE progresses.

We need to come up with a user manual that's specifically for DPE.

**Describe alternatives you've considered**
AutoEdit3 uses Gitbooks - but unfortunately this will not be an option for us (although it's super nice). You'd need to register as a user. We can try and create GitPages instead. <https://pages.github.com/>

**Additional context**

**Comment by allishultes** [comment]
I didn't want to be destructive by going to town on the original file so please see https://paper.dropbox.com/doc/Manual-DPE-Digital-Paper-Edit--BLH~7RSheK9L9vzMzuhSrbMYAg-wd9c7c4Du0etP4m6tp3VD for the latest changes
