### ISSUE TITLE
Register new users

### ISSUE THREAD

**Issue by emettely** [bbc/digital-paper-edit-firebase#145]
@tamsingreen to review the current progress of registering new users and flesh out this ticket. 

**Is your feature request related to a problem? Please describe.**
We want for the user to sign up, and we can choose to "admit" them or not.
This will save a lot of time for us, who maintain DPE.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by emettely** [comment]
Probably can be invalidated as this is implemented in the admin view

**Comment by leihelondon** [comment]
Closing this issue as it's already in the admin view. 

If you log in as admin, then you'll be able to create a new user [here](https://digital-paper-edit-dev.firebaseapp.com/#/admin). Please note that this only allows admins (not every user) to create a new user and the password is also created by the admin. Would be nice to allow users to change password afterwards.
