### ISSUE TITLE
Connect a domain that's linked to BBC

### ISSUE THREAD

**Issue by emettely** [bbc/digital-paper-edit-firebase#147]
**Is your feature request related to a problem? Please describe.**
I think the dev.firebase.app is probably not official sounding as it should be. This may deter users from wanting to use the tool.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by leihelondon** [comment]
Closing this issue as it's redundant. We now have the Firebase app deployed via Cosmos, available on a BBC domain. It's done in https://github.com/bbc/digital-paper-edit-infrastructure/pull/22

https://digital-paper-edit.test.tools.bbc.co.uk/#/
https://digital-paper-edit.tools.bbc.co.uk/#/
