### ISSUE TITLE
Investigation - ADL Export to SaDiE "works"

### ISSUE THREAD

**Issue by emettely** [bbc/digital-paper-edit-firebase#148]
**Is your feature request related to a problem? Please describe.**
Investigate whether the format we have to integrate with SaDiE works. Part of #42 

A user has described that they are able to load the ADL to SaDiE, but the links between the paths are not correct (filename + paths are different), which means loading the project won't "just" work.

**Describe the solution you'd like**
A person with SaDiE desktop app generates an ADL file from DPE tests that the following ADL configurations work when imported to **an existing project**:
1. Dummy UUID with correct filenames
2. Actual UUID with incorrect filenames
3. Actual UUID with correct filenames

**Describe alternatives you've considered**

**Additional context**

**Comment by leihelondon** [comment]
Closing this issue. @SeviSar and @emettely were able to export from DPE and import from SaDiE.
