### ISSUE TITLE
Matomo Analytics Live integration

### ISSUE THREAD

**Issue by emettely** [bbc/digital-paper-edit-firebase#157]
**Is your feature request related to a problem? Please describe.**
Currently analytics is only available in the Test Matomo instance from #155 . It might be nice to have this available in Live Matomo - after the #147 is resolved and we can have separate test + live domains.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by leihelondon** [comment]
Closing this issue as it's redundant. We now have analytics available in the Live Matomo instance.

It's done as part of https://github.com/bbc/digital-paper-edit-infrastructure/pull/22
