### ISSUE TITLE
Spike - investigate what user needs are for FCP: is FCPXML enough? Do we need / can build a plugin or tool they need?

### ISSUE THREAD

**Issue by emettely** [bbc/digital-paper-edit-firebase#167]

**Comment by sarahrainbow** [comment]
Some potential questions to ask FCP users:

* What does your ideal/typical video production process look like? 
    * What order do the following processes typically take place:
        * Media files downloaded
        * EDL created
        * FCP project created
        * Edit within FCP
* What does your file structure for a project look like?
    * Where are media files stored?
    * And the FCP project?
    * Is there a place you would expect to store xml files?
* When exporting the fcpxml from DPE, would the option to download media files be useful?
    * Even if the media files were compressed?

**Comment by leihelondon** [comment]
> Some potential questions to ask FCP users:
> 
> * What does your ideal/typical video production process look like?
>   
>   * What order do the following processes typically take place:
>     
>     * Media files downloaded
>     * EDL created
>     * FCP project created
>     * Edit within FCP
> * What does your file structure for a project look like?
>   
>   * Where are media files stored?
>   * And the FCP project?
>   * Is there a place you would expect to store xml files?
> * When exporting the fcpxml from DPE, would the option to download media files be useful?
>   
>   * Even if the media files were compressed?

This is excellent! Thanks @sarahrainbow What is EDL in this context?

**Comment by sarahrainbow** [comment]
Edit Decision List, so I guess I want to know at which point they'd want to use the DPE tool… let me know if there's a better way of phrasing this!

**Comment by leihelondon** [comment]
I have got in touch with the following people:

[Dave O'Neill](dave.oneill@bbc.co.uk) - Technical Production/Liaison Manager Digital Current Affairs
[Claudia Headon](claudia.headon@bbc.co.uk) - Newsnight online producer. Have helped with Transcriptor research
[Maria Polachowska](maria.polachowska@bbc.co.uk) - Newsnight online producer. Have participated in Transcriptor research
[Carly Wallis](carly.wallis@bbc.co.uk) - TV Current Affairs - Panorama Production Manager
[Jack Willis](jack.willis@bbc.co.uk) - TV Current Affairs - Panorama DIT (Digital imaging technician)

**Comment by leihelondon** [comment]
Got in touch with more people on 14th, April:

[Mike London](michael.london@bbc.co.uk) - News Editor, NEWS-Current Affairs-Travel Show
[Geraldine Ryan](geraldine.ryan@bbc.co.uk) - News Editor, NEWS-Current Affairs-Global Questions
[Simon Hancock](simon.hancock.01@bbc.co.uk) - News Editor, NEWS-Current Affairs-Click
[Lisa Baxter](lisa.baxter@bbc.co.uk) - News Editor, NEWS-Current Affairs-Hardtalk

![image](https://user-images.githubusercontent.com/4565059/114670426-e0128800-9cfa-11eb-9785-9ad6efaaa95d.png)

**Comment by leihelondon** [comment]
Closing this issue. We have spoken to Dave O'Neil. Meeting notes [here](https://paper.dropbox.com/doc/Meeting-notes--BI2ACM6iNR_lr6gbfQqTaZ1jAg-y0uC17h3LHqB7yCEMoYeO).
