### ISSUE TITLE
Evaluate Transcript Editor 2 with DPE

### ISSUE THREAD

**Issue by emettely** [bbc/digital-paper-edit-firebase#168]
**Is your feature request related to a problem? Please describe.**
We want to look at taking advantage of the new [Transcript Editor 2 ](https://github.com/bbc/newslabs-atomic-transcript-editor/projects)that's being developed. 

Eimi to fill: https://paper.dropbox.com/doc/DPE-x-TE-2--BJJ0oi~2K8e5kTYkQAARkEU3Ag-h7n5TMqUdbZt731V6wxNU

**Describe the solution you'd like**
- [ ] Write up an investigation as an ADR (architectural decision record) with an outcome that answers questions:
- Is it beneficial for DPE to integrate with TE2?
- What will it replace?
- Is it feasible within this project cycle?
- [ ] Raise (or don't) tickets that correspond to the outcome
- [ ] Share with team

**Describe alternatives you've considered**

**Additional context**

**Comment by tamsingreen** [comment]
Info from Laurian about TE2: https://newslabs.slack.com/archives/G01FNCCF5TR/p1618823392020400?thread_ts=1618224766.005600&cid=G01FNCCF5TR

**Comment by leihelondon** [comment]
Closing this ticket. Eimi has done a meeting and shared her thoughts [here](https://paper.dropbox.com/doc/DPE-x-TE-2--BJr8N0JeJjdpfD3Vzeiw~tvrAg-h7n5TMqUdbZt731V6wxNU). No decision has been made for which approach to take. This is not the priority for this sprint.
