### ISSUE TITLE
Investigation - SaDiE integration part 2, with users

### ISSUE THREAD

**Issue by emettely** [bbc/digital-paper-edit-firebase#172]
@leihelondon to check with Eimi if this is the same as #148 

**Is your feature request related to a problem? Please describe.**
Depends on #148. This one is about verifying the export and integration - it's sufficient for SaDiE users to be able to actually setup and integrate the ADL into their project.

**Describe the solution you'd like**
- [ ] Investigate and document findings.
- [ ] create tickets from findings, if necessary.

**Describe alternatives you've considered**

**Additional context**

**Comment by leihelondon** [comment]
@tamsingreen and @SeviSar, are there any findings we need to document for the SaDiE export? I remember these's something around file path, is that worth documenting? If not, I'll close this ticket.

**Comment by tamsingreen** [comment]
@leihelondon nothing to document, so closing this ticket.
