### ISSUE TITLE
Bug: Media downloads are corrupt

### ISSUE THREAD

**Issue by tamsingreen** [bbc/digital-paper-edit-firebase#176]
Steps to reproduce:

1. Open existing paper edit
2. From `Export` dropdown, select `Download Media files`
3. Download one media item
4. Once downloaded, try to open media item in any inbuilt media player (quicktime, iTunes)
5. Error appears saying media cannot be opened

After opening the file in VLC media player, it appears that what is actually downloaded is a URi e.g. https://firebasestorage.googleapis.com/v0/b/dev-digital-paper-edit/o/users%2FgLoKESQNkVavUfSiqqoSEEEa6Lo2%2Fuploads%2F0hYX3DeQTo13H9E0xT8I?alt=media&token=2f50b83f-f562-4061-a9d7-4d3b3875b5e4

**Comment by allishultes** [comment]
Possibly relevant:

- Maybe we haven't initialised storage with admin permissions... https://medium.com/firebase-developers/firebase-how-to-access-and-download-files-in-cloud-storage-b8f2cf49aa13
