### ISSUE TITLE
Make contact with potential users for UX research

### ISSUE THREAD

**Issue by tamsingreen** [bbc/digital-paper-edit-firebase#180]

**Comment by leihelondon** [comment]
I have got in touch with the following people on 9th, April:

[Dave O'Neill](dave.oneill@bbc.co.uk) - Technical Production/Liaison Manager Digital Current Affairs (replied)
[Claudia Headon](claudia.headon@bbc.co.uk) - Newsnight online producer. Have helped with Transcriptor research
[Maria Polachowska](maria.polachowska@bbc.co.uk) - Newsnight online producer. Have participated in Transcriptor research
[Carly Wallis](carly.wallis@bbc.co.uk) - TV Current Affairs - Panorama Production Manager
[Jack Willis](jack.willis@bbc.co.uk) - TV Current Affairs - Panorama DIT (Digital imaging technician)

Will wait for their reply and schedule meetings with them.

**Comment by leihelondon** [comment]
Got in touch with more people on 14th, April:

[Mike London](michael.london@bbc.co.uk) - News Editor, NEWS-Current Affairs-Travel Show
[Geraldine Ryan](geraldine.ryan@bbc.co.uk) - News Editor, NEWS-Current Affairs-Global Questions
[Simon Hancock](simon.hancock.01@bbc.co.uk) - News Editor, NEWS-Current Affairs-Click
[Lisa Baxter](lisa.baxter@bbc.co.uk) - News Editor, NEWS-Current Affairs-Hardtalk

![image](https://user-images.githubusercontent.com/4565059/114670426-e0128800-9cfa-11eb-9785-9ad6efaaa95d.png)

**Comment by SeviSar** [comment]
I spoke with Rachael Gillman from Witness and added the notes in the Meeting Notes 
https://paper.dropbox.com/doc/Meeting-notes--BI5kVdyRbVbYsiFwxx39bicQAg-y0uC17h3LHqB7yCEMoYeO

**Comment by leihelondon** [comment]
I've followed up with Dave O'Neill, Claudia Headon and Lisa Baxter to arrange slots. I suggested later this week and next week.

**Comment by SeviSar** [comment]
​​For HardTalk contacted Senior Journalist julia.williams@bbc.co.uk on 20/04

and will be having a chat with Jonathan Glover on Sadie details on 21/04

**Comment by SeviSar** [comment]
If Simon Hancock does not get back happy to try Alan Maloney from Click who I have been working with

**Comment by SeviSar** [comment]
Shall we revive this page, too and link to the meeting notes? https://paper.dropbox.com/doc/Digital-Paper-Edit-Identifying-potential-users--BJOoSO1Wr4ZxwH6UYwn6EEU2Ag-635EC1miqZ2cJy1XshpnH

**Comment by leihelondon** [comment]
Closing this ticket. I've documented the contacts [here](https://paper.dropbox.com/doc/Research-brief-DPE-Export--BKHp2pUgcy_vWk_Nm3cXVLvgAg-eU5VgEhQxuDTT2DsR5APC#:h2=Recruitment-details:).

**Comment by leihelondon** [comment]
> If Simon Hancock does not get back happy to try Alan Maloney from Click who I have been working with

Simon hasn't got back to me. Maybe worth contacting Alan? @SeviSar

**Comment by SeviSar** [comment]
Will do ☺
