### ISSUE TITLE
Speak to Ngan-Thi about user testing plans

### ISSUE THREAD

**Issue by tamsingreen** [bbc/digital-paper-edit-firebase#181]

**Comment by leihelondon** [comment]
Closing this ticket. Tamsin, Sarah, Alli and Lei have spoken to Ngan-Thi. Here's the outcome of the meeting:

- Start contacting editorial people, announcing research and who'd be happy to participate #167 #180
- Fill out research brief #184 
- team reviews the research brief
- Hopes and Fears for the research
- Get the S+SD researchers review brief and consult us on a method
- Discussion guide
- Conducting research, max 45 mins (max. max. 60 mins if people are willing to stay longer)
