### ISSUE TITLE
Knowledge share: how is the Firebase app currently deployed?

### ISSUE THREAD

**Issue by tamsingreen** [bbc/digital-paper-edit-firebase#200]
There are npm scripts to deploy to dev and prod - how do they work behind the scenes? Do they relate only to hosting? Are the cloud functions, Firestore and Cloud Storage set up for dev and prod?

Background knowledge required for https://github.com/bbc/digital-paper-edit-firebase/issues/198 and https://github.com/bbc/digital-paper-edit-firebase/issues/199

**Comment by emettely** [comment]
The convention for test and live environment is "dev" and "prod" in GCP.
In `.firebaserc`, you'll see:
`{
  "projects": {
    "default": "newslabs-dev-aa20",
    "dev": "newslabs-dev-aa20",
    "prod": "newslabs-prod-1a3c"
  }
}
`

It's safe to assume none of the below services are setup for prod:
- Hosting
- Functions
- Storage
- Firestore Rules
- Firestore
- Analytics

The only setup for prod there is is that it's in `package.json`.

**Comment by tamsingreen** [comment]
Closing after knowledge sharing sessions covered this.
