### ISSUE TITLE
Chaos Eimi session

### ISSUE THREAD

**Issue by tamsingreen** [bbc/digital-paper-edit-firebase#202]
Eimi to plan a session where she breaks the app and the team try to fix it.

Notes from the sessions: https://paper.dropbox.com/doc/Chaos-DPE-Session--BJV39pzCJOGHlZv4rF649NrnAQ-DfOuZw0KUSmw2l28KINbD

**Comment by emettely** [comment]
- [x] Misconfigured Domain in API access in GCP Console
- [x] Break runtime config
- [ ] TBD
- [ ] TBD
