### ISSUE TITLE
Review and document existing analytics

### ISSUE THREAD

**Issue by leihelondon** [bbc/digital-paper-edit-firebase#216]
**Context:**
As part of our upcoming [UX research](https://paper.dropbox.com/doc/Research-brief-DPE-Export--BJuLzxVKVNl_uYdeYJ0Fj5GqAg-eU5VgEhQxuDTT2DsR5APC#:uid=188242333801820683281888&h2=Methodology), we'd need to implement all the metrics described [here](https://paper.dropbox.com/doc/Analytics-tracking--BJuERYbQcqbmMLfTRfUpKQy_Ag-Rj39GkJwAcE5E1m1p9QmF). Some metrics have already been implemented as part of https://github.com/bbc/digital-paper-edit-firebase/pull/156

**This ticket is to:**
- Document the existing metrics on [Confluence](https://confluence.dev.bbc.co.uk/display/newslabs/Analytics+overview). See https://github.com/bbc/digital-paper-edit-firebase/pull/156 for reference
- Compare the existing metrics and the [expected metrics](https://paper.dropbox.com/doc/Analytics-tracking--BJuERYbQcqbmMLfTRfUpKQy_Ag-Rj39GkJwAcE5E1m1p9QmF). Update ticket description in #219 with the missing metrics 

**Acceptance criteria:**
- [x] Existing metrics is documented on [Confluence](https://confluence.dev.bbc.co.uk/display/newslabs/Analytics+overview) 
- [x] Discuss the metrics naming conventions with Lei
- [x] #219 is updated with missing metrics to implement.

**Comment by sarahrainbow** [comment]
Further to this ticket, have created #266 outlining additional analytics features including WHOIS and ad blocker

**Comment by tamsingreen** [comment]
These look very thorough. I'd suggest capturing the following too:
Transcript editor view:
- edit transcript [can we do it without firing a million of these]
Help button
Help -> Get in touch with news labs
Help -> View user manual
Programme Script view:
- Pause media in transcript column
- Pause media in script column
- Stop media in script column
- Seek media in transcript column
- Seek media in script column
- Hide transcript
- Hide programme script
Sign out button

otherwise consider this a ✅ from me

**Comment by sarahrainbow** [comment]
Thanks @tamsingreen ! 

Just a couple of questions: 

1. Edit transcript - had the save transcript as a way to capture the transcript edits – do you think it needs more than this?
2. Seek media in transcript column + Seek media in script column – do you mean when users use the search bar to search the transcript? If so I just added it, although can't find a search option in the programme script column?

**Comment by tamsingreen** [comment]
1.  I suppose it was to capture how many edits they were making - but I agree probably the save would be sufficient. happy to take @leihelondon 's opinion on this!
2. seek media: as in click on the playback progress bar to skip to a certain time in the vid. should have added it for the transcript player too - i assume we can hook into the default player controls??

**Comment by leihelondon** [comment]
Closing this ticket. I had a chat with @sarahrainbow and agreed the metrics which are documented [here](https://confluence.dev.bbc.co.uk/display/newslabs/Analytics+overview).
