### ISSUE TITLE
AWS Keys in Commit

### ISSUE THREAD

**Issue by bbc-cloudteam** [bbc/digital-paper-edit-firebase#227]
Hi there,

 We now scan all commits to the BBC repositories for AWS Keys.

 We found the following: AKIAQ4ATLZ.......... found in https://github.com/bbc/digital-paper-edit-firebase/commit/40f46219b63205dea4bc6bd1c86c9870ef92bbc7.

 Please **delete** the keys from the corresponding AWS IAM entity. You can do this by signing into the AWS Console for the given account and following http://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html. Please note that reverting or deleting the git commit, or deactivating the keys within AWS is not sufficient as the credentials have already been exposed. The only mitigation after exposing keys is to explicitly **delete them from AWS**; this is the expected action. Once revoked, or if they are not actual keys, please close this issue to confirm that the keys are void.

Thanks,
Cloud Team
@bbc/otg-tools

**Comment by tamsingreen** [comment]
This key has now been deleted.
