### ISSUE TITLE
Playback doesn't work for Programme Script View on LIVE

### ISSUE THREAD

**Issue by leihelondon** [bbc/digital-paper-edit-firebase#232]
**Context:**
Playback doesn't work for Programme Script view on [LIVE](https://digital-paper-edit.tools.bbc.co.uk/). See screenshot below (notice when the play button is clicked, the media player stays black):

<img width="704" alt="Screen Shot 2021-05-10 at 21 58 20" src="https://user-images.githubusercontent.com/4565059/117672309-a28e0700-b1a1-11eb-9772-f6b347650d12.png">

**To replicate:**
- Log in as admin for live and go to [this link](https://digital-paper-edit.tools.bbc.co.uk/#/projects/cB1rtfHTlExsUf3Purmc/paperedits/OBlnRHllVD6n4QaeuQHS)
- Try to click the play button in the programme script column 

**Please note that this does work on [TEST](https://digital-paper-edit.test.tools.bbc.co.uk/)**

**Comment by tamsingreen** [comment]
Are the wonky ones transcripts created before you set up the prod config?
