### ISSUE TITLE
Browser console errors on LIVE

### ISSUE THREAD

**Issue by leihelondon** [bbc/digital-paper-edit-firebase#233]
When playing with the live site, I saw the following errors in the browser console. I'm using Chrome (Version 90.0.4430.93).

**Error 1:** 
I saw this error when I loaded that page

<img width="1677" alt="Screen Shot 2021-05-10 at 22 00 14" src="https://user-images.githubusercontent.com/4565059/117675573-96f00f80-b1a4-11eb-9da8-7d39a1844152.png">

**Error 2:**
I saw this error when I clicked "+Selection" button:

<img width="1680" alt="Screen Shot 2021-05-10 at 22 01 21" src="https://user-images.githubusercontent.com/4565059/117675730-bc7d1900-b1a4-11eb-9fef-9d836041e294.png">

**Error 3:**
Saw this error when I loaded [this page](https://digital-paper-edit.tools.bbc.co.uk/#/projects/cB1rtfHTlExsUf3Purmc/paperedits/OBlnRHllVD6n4QaeuQHS):
<img width="1680" alt="Screen Shot 2021-05-10 at 22 01 21" src="https://user-images.githubusercontent.com/4565059/117675921-f2ba9880-b1a4-11eb-96cf-56dad9569fb5.png">

I also came across the following error:

<img width="1667" alt="Screen Shot 2021-05-10 at 21 31 01" src="https://user-images.githubusercontent.com/4565059/117676015-0cf47680-b1a5-11eb-8f99-aba0ea0c1eae.png">

**Notes:**

Might be related to #232?

**Comment by allishultes** [comment]
Quick thoughts (WIP): There seems to be a mismatch between the media id and transcript ids for this project in particular. I have identified an issue with GCP storage - we had not set the CORS policy on our storage bucket, which would've been blocking requests to play video files. I've updated this CORS policy now but unfortunately it does not fix this specific issue... related to #232 as well
