### ISSUE TITLE
Implement Paper Edit Firestore Operations

### ISSUE THREAD

**Issue by emettely** [bbc/digital-paper-edit-firebase#25]
**Is your feature request related to a problem? Please describe.**
Paper Edit view currently does not work as it hasn't been ported completely. The NoSQL database (Firestore) does not have any data in it at all either. Referring to the document linked below (there's a defined schema in there that would be of immediate use) and relational DB with real data from the Electron version, we would need to add dummy data of Paper Edits in Firestore to check that Paper Editing is functional and for #24.

**Describe the solution you'd like**
- [x] Please implement CRUD like operations (see [implementation example here](https://github.com/bbc/digital-paper-edit-firebase/blob/master/src/Components/Projects/index.js)) in PaperEdit in Firestore.
- [x] Please convert the Class based React component to React hooks / functions.
- [x] Paper Editing interface does not error out and shows data from Firestore.
- [x] Update the ADR document linked below, if there are any schema changes.
- [x] Please ensure that the Paper Edit interface does not for unauthenticated users.

**Describe alternatives you've considered**

**Additional context**

## Schema ADR
Please refer to the [ADR doc](https://github.com/bbc/digital-paper-edit-firebase/blob/master/docs/ADR/2019-12-02-nosql-schema-security.md#other-schemas) for the NoSQL schema

## PaperEdit Table from Electron
Here is an example JSON for PaperEdit DB in the electron version.
```json
{
        "projectId": "10046281c4ad4938b7d0ae6fa9899bec",
        "title": "Test",
        "description": "",
        "elements": [
            {
                "id": "cjykjmu8q00004q5xwum3p3u2",
                "index": 1,
                "type": "paper-cut",
                "start": 8.01,
                "end": 9.01,
                "speaker": "Soleio Cuervo",
                "words": [
                    {
                        "start": "8.01",
                        "end": "9.01",
                        "text": "company ",
                        "speaker": "Soleio Cuervo",
                        "transcriptId": "1000cjw29xii80000ird74yb19swa"
                    }
                ],
                "transcriptId": "1000cjw29xii80000ird74yb19swa",
                "labelId": []
            },
            {
                "id": "cjykjnko600024q5xm534ubqb",
                "index": 2,
                "type": "paper-cut",
                "start": 120.79,
                "end": 121.48,
                "speaker": "Soleio Cuervo",
                "words": [
                    {
                        "start": "120.79",
                        "end": "121.48",
                        "text": "terminology ",
                        "speaker": "Soleio Cuervo",
                        "transcriptId": "1000cjw29xii80000ird74yb19swa"
                    }
                ],
                "transcriptId": "1000cjw29xii80000ird74yb19swa",
                "labelId": []
            },
            {
                "id": "cjykjnvkc00044q5x8y1np8ea",
                "index": 4,
                "type": "paper-cut",
                "start": 182.76,
                "end": 183.83,
                "speaker": "Soleio Cuervo",
                "words": [
                    {
                        "start": "182.76",
                        "end": "183.83",
                        "text": "Google\u2019s.",
                        "speaker": "Soleio Cuervo",
                        "transcriptId": "1000cjw29xii80000ird74yb19swa"
                    }
                ],
                "transcriptId": "1000cjw29xii80000ird74yb19swa",
                "labelId": []
            },
            {
                "id": "cjykjnzow00054q5xg8qeu3se",
                "index": 5,
                "type": "paper-cut",
                "start": 208.69,
                "end": 208.99,
                "speaker": "Soleio Cuervo",
                "words": [
                    {
                        "start": "208.69",
                        "end": "208.99",
                        "text": "Facebook ",
                        "speaker": "Soleio Cuervo",
                        "transcriptId": "1000cjw29xii80000ird74yb19swa"
                    }
                ],
                "transcriptId": "1000cjw29xii80000ird74yb19swa",
                "labelId": []
            },
            {
                "id": "cjykjo4ub00064q5xm4ot1s0p",
                "index": 6,
                "type": "paper-cut",
                "start": 231.45,
                "end": 231.83,
                "speaker": "Soleio Cuervo",
                "words": [
                    {
                        "start": "231.45",
                        "end": "231.83",
                        "text": "tremendous ",
                        "speaker": "Soleio Cuervo",
                        "transcriptId": "1000cjw29xii80000ird74yb19swa"
                    }
                ],
                "transcriptId": "1000cjw29xii80000ird74yb19swa",
                "labelId": []
            }
        ],
        "created": "Sat Jul 13 2019 18:30:23 GMT+0100 (BST)",
        "_id": "86e938c468de4b0cb873c6e97a3a25f8",
        "id": "86e938c468de4b0cb873c6e97a3a25f8"
    }
```

**Comment by allishultes** [comment]
To refactor the Transcript.js file, we also need to add support for annotations collections, which belong to transcript documents. I spent an hour or so trying to work out why this wasn't working.

I think this ticket is two tickets, with essentially the same list of tasks as above:

1. Get the Transcript component working with annotations and Firestore, etc in the Paper Edit "workspace" (apologies if this language isn't precise)
2. Get the Paper Edit component working with Firestore in the Paper Edit "workspace".

**Comment by emettely** [comment]
I guess in the Transcript component with the Annotations in Firestore can be ignored for now as it can be done as a separate ticket, semi described in #24

**Comment by allishultes** [comment]
TODOs 30/3:

- [ ] Re-render programmeScriptContainer to reflect addition/deletion/modification of programmeScript elements
- [ ] Figure out how to properly pass handleEdit, handleDelete and reorder functions to the ProgrammeScriptContainer component (as it is not allowing expected behaviour)
- [ ] Decide where to implement saving

Quick notes:
- Is ProgrammeScriptContainer not re-rendering on state change because the value (programmeScript) stored in state is passed in as a prop?? Or is it because React does a shallow compare and elements are stored as an array in an object?

**Comment by emettely** [comment]
There's non-stop of re-rendering happening in the parent component of PaperEditor - that's why it's not possible to re-order components.
