### ISSUE TITLE
Admin view not working on live

### ISSUE THREAD

**Issue by allishultes** [bbc/digital-paper-edit-firebase#295]
**Describe the bug**
The admin view doesn't seem to be working on live. 

<img width="1440" alt="Screenshot 2021-07-13 at 14 21 18" src="https://user-images.githubusercontent.com/22618458/125459047-e8246dea-7932-40f6-9674-6453d5ead04b.png">

**To Reproduce**

1. Sign into the admin account
2. Go to https://digital-paper-edit.tools.bbc.co.uk/#/admin
3. See error (i.e., nothing)

**Expected behaviour**
See the test site https://digital-paper-edit.test.tools.bbc.co.uk/#/admin

The tables should be populated.

**Comment by tamsingreen** [comment]
dpe-admin@test.com user in the Firestore database had role "USER" - changed to "ADMIN"
