### ISSUE TITLE
Setup a local dev environment with mocked Firebase

### ISSUE THREAD

**Issue by emettely** [bbc/digital-paper-edit-firebase#31]
**Is your feature request related to a problem? Please describe.**
Our local development environment currently links to an actual Firestore DB in dev environment.
Most often when developing locally, you use the `env` variable to determine which environment you're in. From there, you would need to replace the Firebase SDK to a mocked one.

**Describe the solution you'd like**
- [ ] A local dev environment that uses a mocked database instead of the live one.
- [ ] Document the process [here](https://app.gitbook.com/@textav/s/firebase-react-notes/)
- [ ] Running locally reflects what would be on live
- [ ] Deploying to live reflects what was in local development

**Describe alternatives you've considered**

**Additional context**

**Comment by allishultes** [comment]
*Alternative approach:*

Everyone claim a project id. You are responsible for the data in your project. *Please input test data (for reference check out project MHhZZHXlzvGA9c9ARkEE) and only use your project when working on an issue locally*.

1. @katiaartsenkova:
  - id: PfNZIOsN7E184uep5BBX
  - title: katia 
2. @bennuttall:
  - id: RsUGsIuItsZ1G7QPGoon
  - title: ben  
3. @emettely:
  - id: d8T3QKuhSfWCHxXOVn7Q
  - title: eimi
4. @allishultes:
  - id: wZOkoLAYZgb6RVEj5M4Z
  - title: alli
