### ISSUE TITLE
Implement PreviewCanvas functionality in Paper Edit View

### ISSUE THREAD

**Issue by allishultes** [bbc/digital-paper-edit-firebase#40]
**Is your feature request related to a problem? Please describe.**

Not all of the functionality in the PreviewCanvas component, tied to the ProgrammeScriptContainer in the paper edit view, has been implemented. The code needs to be refactored to render the correct videos from the programme script. This needs to be validated by making sure the UI works with dynamic (not stubbed) data.

_This will require inputting mock data that corresponds to transcript documents into the database._

**Describe the solution you'd like**

- [x] The `getPlaylist` function is not stubbed, but loads data dynamically from Firestore.
- [x] The PreviewCanvas plays clips in the correct order and updates when the programme script is edited. 

**Describe alternatives you've considered**

- N/A

**Additional context**

This is related to #25.

**Comment by allishultes** [comment]
Modifications to schema:

Previously to create playlist clip:

```
          const playlistItem = {
            type: 'video',
            start: startTime,
            sourceStart: element.start,
            duration: element.end - element.start,
            src: transcript.url
          };
```

But `src: transcript.url` was basically trying to load the transcript into the media player. The paper-cut element needs a media object with the url of the video to add to the playlist and the media type.

**Comment by allishultes** [comment]
Something with losing either timing info or re-rendering or not unmounting effecting playback?

**Comment by emettely** [comment]
Added media Link in functions + deployed. See 
mediaUrl "https://www.googleapis.com/download/storage/v1/b/dev-digital-paper-edit/o/users%2FgLoKESQNkVavUfSiqqoSEEEa6Lo2%2Fuploads%2FPCRabGV3AgBFEjuwTPr9?generation=1587018729116453&alt=media"

**Comment by emettely** [comment]
Updates
- [ ] There's some revert audio issue - investigating
- [ ] Also re-discovered a bug in RTE which needs fixing potentially - editing and playing with the first transcript word messes up the timing. Seen startTime for the first word to be something like -61 instead of 0.
- [ ] There's re-rendering issues when removing transcripts from the Paper Edit so going to make sure that works too.

**Comment by emettely** [comment]
Created https://github.com/bbc/digital-paper-edit-storybook/issues/54
