### ISSUE TITLE
Creating new Users

### ISSUE THREAD

**Issue by emettely** [bbc/digital-paper-edit-firebase#83]
**Describe the bug**
Creating new users is done through the interface. We might want to make new Projects for the new user, and assign as ADMIN.

Also noticed that the projects are not being updated in the Users collection - we might want to assign the projects to users when updated.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by allishultes** [comment]
Documentation for manually adding new user is a WIP on branch i83-new-users
